[package]
name = "mach_rs"
version = "0.1.0-alpha"
edition = "2021"
description = "A library to manage Mach port right references and exchange Mach messages."
license = "MIT OR Apache-2.0"

[dependencies]
mach2 = "0.4.1"